# Generated by Django 4.1 on 2022-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='msg',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
