# Generated by Django 3.2.16 on 2022-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0003_info_current_info_total_alter_info_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='msg',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
